[2025-02-21T09:32:14.467+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sync_postgres_to_postgres_transaction_and_amount.process_kafka_amount_messages manual__2025-02-21T09:32:13.921453+00:00 [queued]>
[2025-02-21T09:32:14.481+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sync_postgres_to_postgres_transaction_and_amount.process_kafka_amount_messages manual__2025-02-21T09:32:13.921453+00:00 [queued]>
[2025-02-21T09:32:14.481+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2025-02-21T09:32:14.500+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): process_kafka_amount_messages> on 2025-02-21 09:32:13.921453+00:00
[2025-02-21T09:32:14.509+0000] {standard_task_runner.py:57} INFO - Started process 1532 to run task
[2025-02-21T09:32:14.513+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'sync_postgres_to_postgres_transaction_and_amount', 'process_kafka_amount_messages', 'manual__2025-02-21T09:32:13.921453+00:00', '--job-id', '38', '--raw', '--subdir', 'DAGS_FOLDER/sync_postgres_dag.py', '--cfg-path', '/tmp/tmplw09jgjf']
[2025-02-21T09:32:14.514+0000] {standard_task_runner.py:85} INFO - Job 38: Subtask process_kafka_amount_messages
[2025-02-21T09:32:14.587+0000] {task_command.py:416} INFO - Running <TaskInstance: sync_postgres_to_postgres_transaction_and_amount.process_kafka_amount_messages manual__2025-02-21T09:32:13.921453+00:00 [running]> on host c0c1f1afe7d6
[2025-02-21T09:32:14.702+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sync_postgres_to_postgres_transaction_and_amount' AIRFLOW_CTX_TASK_ID='process_kafka_amount_messages' AIRFLOW_CTX_EXECUTION_DATE='2025-02-21T09:32:13.921453+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-21T09:32:13.921453+00:00'
[2025-02-21T09:32:14.704+0000] {sync_postgres_dag.py:131} INFO - Starting Kafka consumer for amount messages...
[2025-02-21T09:32:14.708+0000] {sync_postgres_dag.py:143} INFO - Connected to Kafka broker at 172.17.0.1:9092
[2025-02-21T09:32:14.715+0000] {sync_postgres_dag.py:148} INFO - Connected to PostgreSQL database at 172.17.0.1:5433
[2025-02-21T09:32:14.717+0000] {sync_postgres_dag.py:162} INFO - Amount table created/verified
[2025-02-21T09:32:39.843+0000] {local_task_job_runner.py:294} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2025-02-21T09:32:39.845+0000] {process_utils.py:131} INFO - Sending 15 to group 1532. PIDs of all processes in the group: [1532]
[2025-02-21T09:32:39.846+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 1532
[2025-02-21T09:32:40.722+0000] {taskinstance.py:1632} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-02-21T09:32:40.723+0000] {sync_postgres_dag.py:215} ERROR - Fatal error in amount consumer: Task received SIGTERM signal
[2025-02-21T09:32:40.723+0000] {sync_postgres_dag.py:219} INFO - Closing connections for amount consumer...
[2025-02-21T09:32:40.783+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=1532, status='terminated', exitcode=0, started='09:32:13') (1532) terminated with exit code 0
