[2025-02-21T07:40:09.915+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sync_postgres_to_postgres_transaction_and_amount.process_kafka_transaction_messages manual__2025-02-21T07:40:09.319036+00:00 [queued]>
[2025-02-21T07:40:09.927+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sync_postgres_to_postgres_transaction_and_amount.process_kafka_transaction_messages manual__2025-02-21T07:40:09.319036+00:00 [queued]>
[2025-02-21T07:40:09.928+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2025-02-21T07:40:09.952+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): process_kafka_transaction_messages> on 2025-02-21 07:40:09.319036+00:00
[2025-02-21T07:40:09.961+0000] {standard_task_runner.py:57} INFO - Started process 381 to run task
[2025-02-21T07:40:09.966+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'sync_postgres_to_postgres_transaction_and_amount', 'process_kafka_transaction_messages', 'manual__2025-02-21T07:40:09.319036+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/sync_postgres_dag.py', '--cfg-path', '/tmp/tmptub408d3']
[2025-02-21T07:40:09.967+0000] {standard_task_runner.py:85} INFO - Job 11: Subtask process_kafka_transaction_messages
[2025-02-21T07:40:10.030+0000] {task_command.py:416} INFO - Running <TaskInstance: sync_postgres_to_postgres_transaction_and_amount.process_kafka_transaction_messages manual__2025-02-21T07:40:09.319036+00:00 [running]> on host e5982255e08e
[2025-02-21T07:40:10.133+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sync_postgres_to_postgres_transaction_and_amount' AIRFLOW_CTX_TASK_ID='process_kafka_transaction_messages' AIRFLOW_CTX_EXECUTION_DATE='2025-02-21T07:40:09.319036+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-21T07:40:09.319036+00:00'
[2025-02-21T07:40:10.135+0000] {sync_postgres_dag.py:27} INFO - Starting Kafka consumer for transaction messages...
[2025-02-21T07:40:10.137+0000] {conn.py:380} INFO - <BrokerConnection node_id=bootstrap-0 host=172.17.0.1:9092 <connecting> [IPv4 ('172.17.0.1', 9092)]>: connecting to 172.17.0.1:9092 [('172.17.0.1', 9092) IPv4]
[2025-02-21T07:40:10.138+0000] {conn.py:1206} INFO - Probing node bootstrap-0 broker version
[2025-02-21T07:40:10.138+0000] {conn.py:410} INFO - <BrokerConnection node_id=bootstrap-0 host=172.17.0.1:9092 <connecting> [IPv4 ('172.17.0.1', 9092)]>: Connection complete.
[2025-02-21T07:40:10.244+0000] {conn.py:1268} INFO - Broker version identified as 2.6.0
[2025-02-21T07:40:10.245+0000] {conn.py:1269} INFO - Set configuration api_version=(2, 6, 0) to skip auto check_version requests on startup
[2025-02-21T07:40:10.246+0000] {subscription_state.py:171} INFO - Updating subscribed topics to: ('from_mysql_transaction',)
[2025-02-21T07:40:10.247+0000] {sync_postgres_dag.py:38} INFO - Connected to Kafka broker at 172.17.0.1:9092
[2025-02-21T07:40:10.253+0000] {sync_postgres_dag.py:43} INFO - Connected to PostgreSQL database at 172.17.0.1:5433
[2025-02-21T07:40:10.291+0000] {sync_postgres_dag.py:58} INFO - Transaction table created/verified
[2025-02-21T07:40:10.294+0000] {cluster.py:371} INFO - Group coordinator for transaction_consumer_group is ('coordinator-1', '172.25.0.5', 9092, None)
[2025-02-21T07:40:10.295+0000] {base.py:693} INFO - Discovered coordinator coordinator-1 for group transaction_consumer_group
[2025-02-21T07:40:10.295+0000] {base.py:741} INFO - Starting new heartbeat thread
[2025-02-21T07:40:10.296+0000] {consumer.py:348} INFO - Revoking previously assigned partitions () for group transaction_consumer_group
[2025-02-21T07:40:10.297+0000] {conn.py:380} INFO - <BrokerConnection node_id=coordinator-1 host=172.25.0.5:9092 <connecting> [IPv4 ('172.25.0.5', 9092)]>: connecting to 172.25.0.5:9092 [('172.25.0.5', 9092) IPv4]
[2025-02-21T07:42:26.579+0000] {conn.py:418} ERROR - Connect attempt to <BrokerConnection node_id=coordinator-1 host=172.25.0.5:9092 <connecting> [IPv4 ('172.25.0.5', 9092)]> returned error 110. Disconnecting.
[2025-02-21T07:42:26.580+0000] {conn.py:919} ERROR - <BrokerConnection node_id=coordinator-1 host=172.25.0.5:9092 <connecting> [IPv4 ('172.25.0.5', 9092)]>: Closing connection. KafkaConnectionError: 110 ETIMEDOUT
[2025-02-21T07:42:26.580+0000] {client_async.py:331} WARNING - Node coordinator-1 connection failed -- refreshing metadata
[2025-02-21T07:42:26.681+0000] {base.py:715} WARNING - Marking the coordinator dead (node coordinator-1) for group transaction_consumer_group: Node Disconnected.
[2025-02-21T07:42:26.682+0000] {conn.py:380} INFO - <BrokerConnection node_id=1 host=172.25.0.5:9092 <connecting> [IPv4 ('172.25.0.5', 9092)]>: connecting to 172.25.0.5:9092 [('172.25.0.5', 9092) IPv4]
[2025-02-21T07:42:36.743+0000] {local_task_job_runner.py:294} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2025-02-21T07:42:36.747+0000] {process_utils.py:131} INFO - Sending 15 to group 381. PIDs of all processes in the group: [381]
[2025-02-21T07:42:36.747+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 381
[2025-02-21T07:42:36.748+0000] {taskinstance.py:1632} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-02-21T07:42:36.748+0000] {sync_postgres_dag.py:110} ERROR - Fatal error in transaction consumer: Task received SIGTERM signal
[2025-02-21T07:42:36.749+0000] {sync_postgres_dag.py:114} INFO - Closing connections for transaction consumer...
[2025-02-21T07:42:36.750+0000] {base.py:748} INFO - Stopping heartbeat thread
[2025-02-21T07:42:36.751+0000] {conn.py:919} INFO - <BrokerConnection node_id=bootstrap-0 host=172.17.0.1:9092 <connected> [IPv4 ('172.17.0.1', 9092)]>: Closing connection. 
[2025-02-21T07:42:36.751+0000] {conn.py:919} INFO - <BrokerConnection node_id=1 host=172.25.0.5:9092 <connecting> [IPv4 ('172.25.0.5', 9092)]>: Closing connection. 
[2025-02-21T07:42:36.801+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=381, status='terminated', exitcode=0, started='07:40:09') (381) terminated with exit code 0
