[2025-02-21T07:37:23.817+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sync_postgres_to_postgres_transaction_and_amount.process_kafka_transaction_messages manual__2025-02-21T07:37:22.615105+00:00 [queued]>
[2025-02-21T07:37:23.830+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sync_postgres_to_postgres_transaction_and_amount.process_kafka_transaction_messages manual__2025-02-21T07:37:22.615105+00:00 [queued]>
[2025-02-21T07:37:23.831+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2025-02-21T07:37:23.846+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): process_kafka_transaction_messages> on 2025-02-21 07:37:22.615105+00:00
[2025-02-21T07:37:23.855+0000] {standard_task_runner.py:57} INFO - Started process 333 to run task
[2025-02-21T07:37:23.866+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'sync_postgres_to_postgres_transaction_and_amount', 'process_kafka_transaction_messages', 'manual__2025-02-21T07:37:22.615105+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/sync_postgres_dag.py', '--cfg-path', '/tmp/tmpoh5bwldq']
[2025-02-21T07:37:23.868+0000] {standard_task_runner.py:85} INFO - Job 7: Subtask process_kafka_transaction_messages
[2025-02-21T07:37:23.967+0000] {task_command.py:416} INFO - Running <TaskInstance: sync_postgres_to_postgres_transaction_and_amount.process_kafka_transaction_messages manual__2025-02-21T07:37:22.615105+00:00 [running]> on host e5982255e08e
[2025-02-21T07:37:24.093+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sync_postgres_to_postgres_transaction_and_amount' AIRFLOW_CTX_TASK_ID='process_kafka_transaction_messages' AIRFLOW_CTX_EXECUTION_DATE='2025-02-21T07:37:22.615105+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-21T07:37:22.615105+00:00'
[2025-02-21T07:37:24.096+0000] {sync_postgres_dag.py:27} INFO - Starting Kafka consumer for transaction messages...
[2025-02-21T07:37:24.102+0000] {conn.py:380} INFO - <BrokerConnection node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-02-21T07:37:24.102+0000] {conn.py:1206} INFO - Probing node bootstrap-0 broker version
[2025-02-21T07:37:24.103+0000] {conn.py:418} ERROR - Connect attempt to <BrokerConnection node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]> returned error 111. Disconnecting.
[2025-02-21T07:37:24.104+0000] {conn.py:919} ERROR - <BrokerConnection node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-02-21T07:37:24.151+0000] {conn.py:380} INFO - <BrokerConnection node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-02-21T07:37:24.152+0000] {conn.py:418} ERROR - Connect attempt to <BrokerConnection node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]> returned error 111. Disconnecting.
[2025-02-21T07:37:24.153+0000] {conn.py:919} ERROR - <BrokerConnection node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-02-21T07:37:24.201+0000] {conn.py:380} INFO - <BrokerConnection node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-02-21T07:37:24.202+0000] {conn.py:418} ERROR - Connect attempt to <BrokerConnection node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]> returned error 111. Disconnecting.
[2025-02-21T07:37:24.202+0000] {conn.py:919} ERROR - <BrokerConnection node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-02-21T07:37:24.203+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/sync_postgres_dag.py", line 29, in process_kafka_transaction_messages
    consumer = KafkaConsumer(
  File "/home/airflow/.local/lib/python3.8/site-packages/kafka/consumer/group.py", line 358, in __init__
    self._client = self.config['kafka_client'](metrics=self._metrics, **self.config)
  File "/home/airflow/.local/lib/python3.8/site-packages/kafka/client_async.py", line 244, in __init__
    self.config['api_version'] = self.check_version(timeout=check_timeout)
  File "/home/airflow/.local/lib/python3.8/site-packages/kafka/client_async.py", line 900, in check_version
    raise Errors.NoBrokersAvailable()
kafka.errors.NoBrokersAvailable: NoBrokersAvailable
[2025-02-21T07:37:24.223+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=sync_postgres_to_postgres_transaction_and_amount, task_id=process_kafka_transaction_messages, execution_date=20250221T073722, start_date=20250221T073723, end_date=20250221T073724
[2025-02-21T07:37:24.244+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 7 for task process_kafka_transaction_messages (NoBrokersAvailable; 333)
[2025-02-21T07:37:24.275+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-02-21T07:37:24.310+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
