[2025-02-21T08:15:26.937+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sync_mysql_to_postgres_transaction_and_amount.process_kafka_transaction_messages manual__2025-02-21T08:15:25.620662+00:00 [queued]>
[2025-02-21T08:15:26.955+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sync_mysql_to_postgres_transaction_and_amount.process_kafka_transaction_messages manual__2025-02-21T08:15:25.620662+00:00 [queued]>
[2025-02-21T08:15:26.955+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2025-02-21T08:15:26.975+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): process_kafka_transaction_messages> on 2025-02-21 08:15:25.620662+00:00
[2025-02-21T08:15:26.986+0000] {standard_task_runner.py:57} INFO - Started process 314 to run task
[2025-02-21T08:15:26.993+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'sync_mysql_to_postgres_transaction_and_amount', 'process_kafka_transaction_messages', 'manual__2025-02-21T08:15:25.620662+00:00', '--job-id', '26', '--raw', '--subdir', 'DAGS_FOLDER/sync_mysql_dag.py', '--cfg-path', '/tmp/tmp_vptk_pn']
[2025-02-21T08:15:26.996+0000] {standard_task_runner.py:85} INFO - Job 26: Subtask process_kafka_transaction_messages
[2025-02-21T08:15:27.114+0000] {task_command.py:416} INFO - Running <TaskInstance: sync_mysql_to_postgres_transaction_and_amount.process_kafka_transaction_messages manual__2025-02-21T08:15:25.620662+00:00 [running]> on host c0c1f1afe7d6
[2025-02-21T08:15:27.232+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sync_mysql_to_postgres_transaction_and_amount' AIRFLOW_CTX_TASK_ID='process_kafka_transaction_messages' AIRFLOW_CTX_EXECUTION_DATE='2025-02-21T08:15:25.620662+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-21T08:15:25.620662+00:00'
[2025-02-21T08:15:27.233+0000] {sync_mysql_dag.py:27} INFO - Starting Kafka consumer for transaction messages...
[2025-02-21T08:15:27.237+0000] {sync_mysql_dag.py:39} INFO - Connected to Kafka broker at 172.17.0.1:9092
[2025-02-21T08:15:27.242+0000] {sync_mysql_dag.py:44} INFO - Connected to PostgreSQL database at 172.17.0.1:5433
[2025-02-21T08:15:27.244+0000] {sync_mysql_dag.py:59} INFO - Transaction table created/verified
[2025-02-21T08:23:33.002+0000] {local_task_job_runner.py:294} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2025-02-21T08:23:33.004+0000] {process_utils.py:131} INFO - Sending 15 to group 314. PIDs of all processes in the group: [314]
[2025-02-21T08:23:33.005+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 314
[2025-02-21T08:23:33.340+0000] {taskinstance.py:1632} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-02-21T08:23:33.340+0000] {sync_mysql_dag.py:120} ERROR - Fatal error in transaction consumer: Task received SIGTERM signal
[2025-02-21T08:23:33.341+0000] {sync_mysql_dag.py:124} INFO - Closing connections for transaction consumer...
[2025-02-21T08:23:33.419+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=314, status='terminated', exitcode=0, started='08:15:26') (314) terminated with exit code 0
