[2025-02-26T08:56:04.541+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: run_docker_container_dag.run_python_script manual__2025-02-26T08:56:02.923379+00:00 [queued]>
[2025-02-26T08:56:04.557+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: run_docker_container_dag.run_python_script manual__2025-02-26T08:56:02.923379+00:00 [queued]>
[2025-02-26T08:56:04.557+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-02-26T08:56:04.575+0000] {taskinstance.py:1382} INFO - Executing <Task(DockerOperator): run_python_script> on 2025-02-26 08:56:02.923379+00:00
[2025-02-26T08:56:04.585+0000] {standard_task_runner.py:57} INFO - Started process 485 to run task
[2025-02-26T08:56:04.589+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'run_docker_container_dag', 'run_python_script', 'manual__2025-02-26T08:56:02.923379+00:00', '--job-id', '57', '--raw', '--subdir', 'DAGS_FOLDER/test_docker.py', '--cfg-path', '/tmp/tmp1biu8j63']
[2025-02-26T08:56:04.591+0000] {standard_task_runner.py:85} INFO - Job 57: Subtask run_python_script
[2025-02-26T08:56:04.666+0000] {task_command.py:416} INFO - Running <TaskInstance: run_docker_container_dag.run_python_script manual__2025-02-26T08:56:02.923379+00:00 [running]> on host 09c7d6597690
[2025-02-26T08:56:04.786+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='run_docker_container_dag' AIRFLOW_CTX_TASK_ID='run_python_script' AIRFLOW_CTX_EXECUTION_DATE='2025-02-26T08:56:02.923379+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-26T08:56:02.923379+00:00'
[2025-02-26T08:56:04.820+0000] {docker.py:343} INFO - Starting docker container from image list-files-app
[2025-02-26T08:56:04.825+0000] {docker.py:351} WARNING - Using remote engine or docker-in-docker and mounting temporary volume from host is not supported. Falling back to `mount_tmp_dir=False` mode. You can set `mount_tmp_dir` parameter to False to disable mounting and remove the warning
[2025-02-26T08:56:05.221+0000] {docker.py:413} INFO - Files in directory:
test.txt
test3.txt
The file 'test.txt' exists in the directory.
[2025-02-26T08:56:05.426+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=run_docker_container_dag, task_id=run_python_script, execution_date=20250226T085602, start_date=20250226T085604, end_date=20250226T085605
[2025-02-26T08:56:05.491+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-02-26T08:56:05.516+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
