[2025-02-20T04:44:05.774+0000] {processor.py:157} INFO - Started process (PID=3455) to work on /opt/airflow/dags/sync_postgres_dag.py
[2025-02-20T04:44:05.775+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sync_postgres_dag.py for tasks to queue
[2025-02-20T04:44:05.778+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:44:05.777+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/sync_postgres_dag.py
[2025-02-20T04:44:05.787+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:44:05.784+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/sync_postgres_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sync_postgres_dag.py", line 4, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2025-02-20T04:44:05.788+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sync_postgres_dag.py
[2025-02-20T04:44:05.819+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sync_postgres_dag.py took 0.049 seconds
[2025-02-20T04:44:36.035+0000] {processor.py:157} INFO - Started process (PID=3463) to work on /opt/airflow/dags/sync_postgres_dag.py
[2025-02-20T04:44:36.036+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sync_postgres_dag.py for tasks to queue
[2025-02-20T04:44:36.039+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:44:36.038+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/sync_postgres_dag.py
[2025-02-20T04:44:36.047+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:44:36.045+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/sync_postgres_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sync_postgres_dag.py", line 4, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2025-02-20T04:44:36.048+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sync_postgres_dag.py
[2025-02-20T04:44:36.088+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sync_postgres_dag.py took 0.058 seconds
[2025-02-20T04:45:06.304+0000] {processor.py:157} INFO - Started process (PID=3472) to work on /opt/airflow/dags/sync_postgres_dag.py
[2025-02-20T04:45:06.306+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sync_postgres_dag.py for tasks to queue
[2025-02-20T04:45:06.309+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:45:06.308+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/sync_postgres_dag.py
[2025-02-20T04:45:06.313+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:45:06.312+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/sync_postgres_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sync_postgres_dag.py", line 4, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2025-02-20T04:45:06.314+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sync_postgres_dag.py
[2025-02-20T04:45:06.348+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sync_postgres_dag.py took 0.048 seconds
[2025-02-20T04:45:36.573+0000] {processor.py:157} INFO - Started process (PID=3481) to work on /opt/airflow/dags/sync_postgres_dag.py
[2025-02-20T04:45:36.575+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sync_postgres_dag.py for tasks to queue
[2025-02-20T04:45:36.578+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:45:36.577+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/sync_postgres_dag.py
[2025-02-20T04:45:36.582+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:45:36.581+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/sync_postgres_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sync_postgres_dag.py", line 4, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2025-02-20T04:45:36.583+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sync_postgres_dag.py
[2025-02-20T04:45:36.617+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sync_postgres_dag.py took 0.048 seconds
[2025-02-20T04:46:06.828+0000] {processor.py:157} INFO - Started process (PID=3490) to work on /opt/airflow/dags/sync_postgres_dag.py
[2025-02-20T04:46:06.830+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sync_postgres_dag.py for tasks to queue
[2025-02-20T04:46:06.832+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:46:06.832+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/sync_postgres_dag.py
[2025-02-20T04:46:06.837+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:46:06.836+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/sync_postgres_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sync_postgres_dag.py", line 4, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2025-02-20T04:46:06.837+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sync_postgres_dag.py
[2025-02-20T04:46:06.868+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sync_postgres_dag.py took 0.043 seconds
[2025-02-20T04:46:37.109+0000] {processor.py:157} INFO - Started process (PID=3499) to work on /opt/airflow/dags/sync_postgres_dag.py
[2025-02-20T04:46:37.110+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sync_postgres_dag.py for tasks to queue
[2025-02-20T04:46:37.113+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:46:37.113+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/sync_postgres_dag.py
[2025-02-20T04:46:37.118+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:46:37.117+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/sync_postgres_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sync_postgres_dag.py", line 4, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2025-02-20T04:46:37.119+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sync_postgres_dag.py
[2025-02-20T04:46:37.154+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sync_postgres_dag.py took 0.050 seconds
[2025-02-20T04:46:47.216+0000] {processor.py:157} INFO - Started process (PID=3507) to work on /opt/airflow/dags/sync_postgres_dag.py
[2025-02-20T04:46:47.218+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sync_postgres_dag.py for tasks to queue
[2025-02-20T04:46:47.220+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:46:47.220+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/sync_postgres_dag.py
[2025-02-20T04:46:47.227+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:46:47.226+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/sync_postgres_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sync_postgres_dag.py", line 4, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2025-02-20T04:46:47.227+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sync_postgres_dag.py
[2025-02-20T04:46:47.253+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sync_postgres_dag.py took 0.041 seconds
[2025-02-20T04:47:07.394+0000] {processor.py:157} INFO - Started process (PID=3509) to work on /opt/airflow/dags/sync_postgres_dag.py
[2025-02-20T04:47:07.395+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sync_postgres_dag.py for tasks to queue
[2025-02-20T04:47:07.397+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:47:07.397+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/sync_postgres_dag.py
[2025-02-20T04:47:07.407+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:47:07.405+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/sync_postgres_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sync_postgres_dag.py", line 4, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2025-02-20T04:47:07.408+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sync_postgres_dag.py
[2025-02-20T04:47:07.443+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sync_postgres_dag.py took 0.054 seconds
[2025-02-20T04:47:36.689+0000] {processor.py:157} INFO - Started process (PID=3518) to work on /opt/airflow/dags/sync_postgres_dag.py
[2025-02-20T04:47:36.691+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sync_postgres_dag.py for tasks to queue
[2025-02-20T04:47:36.694+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:47:36.693+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/sync_postgres_dag.py
[2025-02-20T04:47:36.701+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:47:36.699+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/sync_postgres_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sync_postgres_dag.py", line 4, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2025-02-20T04:47:36.702+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sync_postgres_dag.py
[2025-02-20T04:47:36.739+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sync_postgres_dag.py took 0.056 seconds
[2025-02-20T04:47:45.801+0000] {processor.py:157} INFO - Started process (PID=3527) to work on /opt/airflow/dags/sync_postgres_dag.py
[2025-02-20T04:47:45.802+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sync_postgres_dag.py for tasks to queue
[2025-02-20T04:47:45.805+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:47:45.805+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/sync_postgres_dag.py
[2025-02-20T04:47:45.813+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:47:45.812+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/sync_postgres_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sync_postgres_dag.py", line 4, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2025-02-20T04:47:45.813+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sync_postgres_dag.py
[2025-02-20T04:47:45.844+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sync_postgres_dag.py took 0.047 seconds
[2025-02-20T04:47:52.866+0000] {processor.py:157} INFO - Started process (PID=3528) to work on /opt/airflow/dags/sync_postgres_dag.py
[2025-02-20T04:47:52.868+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sync_postgres_dag.py for tasks to queue
[2025-02-20T04:47:52.871+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:47:52.871+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/sync_postgres_dag.py
[2025-02-20T04:47:52.878+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:47:52.876+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/sync_postgres_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sync_postgres_dag.py", line 4, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2025-02-20T04:47:52.879+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sync_postgres_dag.py
[2025-02-20T04:47:52.911+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sync_postgres_dag.py took 0.050 seconds
[2025-02-20T04:48:01.969+0000] {processor.py:157} INFO - Started process (PID=3529) to work on /opt/airflow/dags/sync_postgres_dag.py
[2025-02-20T04:48:01.970+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sync_postgres_dag.py for tasks to queue
[2025-02-20T04:48:01.974+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:48:01.973+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/sync_postgres_dag.py
[2025-02-20T04:48:01.981+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:48:01.980+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/sync_postgres_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sync_postgres_dag.py", line 4, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2025-02-20T04:48:01.982+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sync_postgres_dag.py
[2025-02-20T04:48:02.017+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sync_postgres_dag.py took 0.052 seconds
[2025-02-20T04:48:04.013+0000] {processor.py:157} INFO - Started process (PID=3530) to work on /opt/airflow/dags/sync_postgres_dag.py
[2025-02-20T04:48:04.015+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sync_postgres_dag.py for tasks to queue
[2025-02-20T04:48:04.017+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:48:04.017+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/sync_postgres_dag.py
[2025-02-20T04:48:04.024+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:48:04.023+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/sync_postgres_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sync_postgres_dag.py", line 4, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2025-02-20T04:48:04.025+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sync_postgres_dag.py
[2025-02-20T04:48:04.061+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sync_postgres_dag.py took 0.051 seconds
[2025-02-20T04:48:06.075+0000] {processor.py:157} INFO - Started process (PID=3531) to work on /opt/airflow/dags/sync_postgres_dag.py
[2025-02-20T04:48:06.076+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sync_postgres_dag.py for tasks to queue
[2025-02-20T04:48:06.078+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:48:06.078+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/sync_postgres_dag.py
[2025-02-20T04:48:06.090+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:48:06.085+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/sync_postgres_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sync_postgres_dag.py", line 4, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2025-02-20T04:48:06.091+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sync_postgres_dag.py
[2025-02-20T04:48:06.127+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sync_postgres_dag.py took 0.056 seconds
[2025-02-20T04:48:12.188+0000] {processor.py:157} INFO - Started process (PID=3540) to work on /opt/airflow/dags/sync_postgres_dag.py
[2025-02-20T04:48:12.190+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sync_postgres_dag.py for tasks to queue
[2025-02-20T04:48:12.193+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:48:12.193+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/sync_postgres_dag.py
[2025-02-20T04:48:12.200+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:48:12.199+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/sync_postgres_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sync_postgres_dag.py", line 4, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2025-02-20T04:48:12.201+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sync_postgres_dag.py
[2025-02-20T04:48:12.237+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sync_postgres_dag.py took 0.053 seconds
[2025-02-20T04:48:22.298+0000] {processor.py:157} INFO - Started process (PID=3541) to work on /opt/airflow/dags/sync_postgres_dag.py
[2025-02-20T04:48:22.299+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sync_postgres_dag.py for tasks to queue
[2025-02-20T04:48:22.301+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:48:22.301+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/sync_postgres_dag.py
[2025-02-20T04:48:22.307+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:48:22.306+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/sync_postgres_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sync_postgres_dag.py", line 4, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2025-02-20T04:48:22.308+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sync_postgres_dag.py
[2025-02-20T04:48:22.338+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sync_postgres_dag.py took 0.043 seconds
[2025-02-20T04:48:52.659+0000] {processor.py:157} INFO - Started process (PID=3552) to work on /opt/airflow/dags/sync_postgres_dag.py
[2025-02-20T04:48:52.664+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sync_postgres_dag.py for tasks to queue
[2025-02-20T04:48:52.667+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:48:52.667+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/sync_postgres_dag.py
[2025-02-20T04:48:52.673+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:48:52.672+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/sync_postgres_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sync_postgres_dag.py", line 4, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2025-02-20T04:48:52.673+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sync_postgres_dag.py
[2025-02-20T04:48:52.708+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sync_postgres_dag.py took 0.053 seconds
[2025-02-20T04:48:54.731+0000] {processor.py:157} INFO - Started process (PID=3553) to work on /opt/airflow/dags/sync_postgres_dag.py
[2025-02-20T04:48:54.732+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sync_postgres_dag.py for tasks to queue
[2025-02-20T04:48:54.735+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:48:54.734+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/sync_postgres_dag.py
[2025-02-20T04:48:54.742+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:48:54.740+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/sync_postgres_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sync_postgres_dag.py", line 4, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2025-02-20T04:48:54.742+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sync_postgres_dag.py
[2025-02-20T04:48:54.772+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sync_postgres_dag.py took 0.046 seconds
[2025-02-20T04:49:24.971+0000] {processor.py:157} INFO - Started process (PID=3562) to work on /opt/airflow/dags/sync_postgres_dag.py
[2025-02-20T04:49:24.972+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sync_postgres_dag.py for tasks to queue
[2025-02-20T04:49:24.975+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:49:24.974+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/sync_postgres_dag.py
[2025-02-20T04:49:24.979+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:49:24.978+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/sync_postgres_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sync_postgres_dag.py", line 4, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2025-02-20T04:49:24.979+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sync_postgres_dag.py
[2025-02-20T04:49:25.012+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sync_postgres_dag.py took 0.044 seconds
[2025-02-20T04:49:55.233+0000] {processor.py:157} INFO - Started process (PID=3571) to work on /opt/airflow/dags/sync_postgres_dag.py
[2025-02-20T04:49:55.235+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sync_postgres_dag.py for tasks to queue
[2025-02-20T04:49:55.238+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:49:55.237+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/sync_postgres_dag.py
[2025-02-20T04:49:55.243+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:49:55.241+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/sync_postgres_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sync_postgres_dag.py", line 4, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2025-02-20T04:49:55.243+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sync_postgres_dag.py
[2025-02-20T04:49:55.272+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sync_postgres_dag.py took 0.043 seconds
[2025-02-20T04:50:25.479+0000] {processor.py:157} INFO - Started process (PID=3580) to work on /opt/airflow/dags/sync_postgres_dag.py
[2025-02-20T04:50:25.480+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sync_postgres_dag.py for tasks to queue
[2025-02-20T04:50:25.483+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:50:25.483+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/sync_postgres_dag.py
[2025-02-20T04:50:25.488+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:50:25.487+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/sync_postgres_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sync_postgres_dag.py", line 4, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2025-02-20T04:50:25.488+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sync_postgres_dag.py
[2025-02-20T04:50:25.518+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sync_postgres_dag.py took 0.043 seconds
[2025-02-20T04:50:55.748+0000] {processor.py:157} INFO - Started process (PID=3589) to work on /opt/airflow/dags/sync_postgres_dag.py
[2025-02-20T04:50:55.749+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sync_postgres_dag.py for tasks to queue
[2025-02-20T04:50:55.752+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:50:55.751+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/sync_postgres_dag.py
[2025-02-20T04:50:55.756+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:50:55.755+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/sync_postgres_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sync_postgres_dag.py", line 4, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2025-02-20T04:50:55.756+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sync_postgres_dag.py
[2025-02-20T04:50:55.793+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sync_postgres_dag.py took 0.049 seconds
[2025-02-20T04:51:26.016+0000] {processor.py:157} INFO - Started process (PID=3598) to work on /opt/airflow/dags/sync_postgres_dag.py
[2025-02-20T04:51:26.043+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sync_postgres_dag.py for tasks to queue
[2025-02-20T04:51:26.047+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:51:26.046+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/sync_postgres_dag.py
[2025-02-20T04:51:26.053+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:51:26.052+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/sync_postgres_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sync_postgres_dag.py", line 4, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2025-02-20T04:51:26.054+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sync_postgres_dag.py
[2025-02-20T04:51:26.080+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sync_postgres_dag.py took 0.069 seconds
[2025-02-20T04:51:56.292+0000] {processor.py:157} INFO - Started process (PID=3607) to work on /opt/airflow/dags/sync_postgres_dag.py
[2025-02-20T04:51:56.293+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sync_postgres_dag.py for tasks to queue
[2025-02-20T04:51:56.296+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:51:56.295+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/sync_postgres_dag.py
[2025-02-20T04:51:56.300+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:51:56.299+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/sync_postgres_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sync_postgres_dag.py", line 4, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2025-02-20T04:51:56.300+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sync_postgres_dag.py
[2025-02-20T04:51:56.331+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sync_postgres_dag.py took 0.043 seconds
[2025-02-20T04:52:26.514+0000] {processor.py:157} INFO - Started process (PID=3616) to work on /opt/airflow/dags/sync_postgres_dag.py
[2025-02-20T04:52:26.542+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sync_postgres_dag.py for tasks to queue
[2025-02-20T04:52:26.545+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:52:26.544+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/sync_postgres_dag.py
[2025-02-20T04:52:26.550+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:52:26.549+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/sync_postgres_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sync_postgres_dag.py", line 4, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2025-02-20T04:52:26.551+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sync_postgres_dag.py
[2025-02-20T04:52:26.580+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sync_postgres_dag.py took 0.070 seconds
[2025-02-20T04:52:56.781+0000] {processor.py:157} INFO - Started process (PID=3625) to work on /opt/airflow/dags/sync_postgres_dag.py
[2025-02-20T04:52:56.782+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sync_postgres_dag.py for tasks to queue
[2025-02-20T04:52:56.785+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:52:56.784+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/sync_postgres_dag.py
[2025-02-20T04:52:56.790+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:52:56.789+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/sync_postgres_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sync_postgres_dag.py", line 4, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2025-02-20T04:52:56.791+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sync_postgres_dag.py
[2025-02-20T04:52:56.821+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sync_postgres_dag.py took 0.044 seconds
[2025-02-20T04:53:27.025+0000] {processor.py:157} INFO - Started process (PID=3634) to work on /opt/airflow/dags/sync_postgres_dag.py
[2025-02-20T04:53:27.042+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sync_postgres_dag.py for tasks to queue
[2025-02-20T04:53:27.045+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:53:27.045+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/sync_postgres_dag.py
[2025-02-20T04:53:27.049+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:53:27.048+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/sync_postgres_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sync_postgres_dag.py", line 4, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2025-02-20T04:53:27.050+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sync_postgres_dag.py
[2025-02-20T04:53:27.462+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sync_postgres_dag.py took 0.441 seconds
[2025-02-20T04:53:58.279+0000] {processor.py:157} INFO - Started process (PID=3643) to work on /opt/airflow/dags/sync_postgres_dag.py
[2025-02-20T04:53:58.281+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sync_postgres_dag.py for tasks to queue
[2025-02-20T04:53:58.284+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:53:58.284+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/sync_postgres_dag.py
[2025-02-20T04:53:58.292+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:53:58.290+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/sync_postgres_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sync_postgres_dag.py", line 4, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2025-02-20T04:53:58.293+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sync_postgres_dag.py
[2025-02-20T04:53:58.326+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sync_postgres_dag.py took 0.050 seconds
[2025-02-20T04:54:28.567+0000] {processor.py:157} INFO - Started process (PID=3652) to work on /opt/airflow/dags/sync_postgres_dag.py
[2025-02-20T04:54:28.568+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sync_postgres_dag.py for tasks to queue
[2025-02-20T04:54:28.571+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:54:28.570+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/sync_postgres_dag.py
[2025-02-20T04:54:28.576+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:54:28.574+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/sync_postgres_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sync_postgres_dag.py", line 4, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2025-02-20T04:54:28.576+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sync_postgres_dag.py
[2025-02-20T04:54:28.613+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sync_postgres_dag.py took 0.050 seconds
[2025-02-20T04:54:58.826+0000] {processor.py:157} INFO - Started process (PID=3661) to work on /opt/airflow/dags/sync_postgres_dag.py
[2025-02-20T04:54:58.829+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sync_postgres_dag.py for tasks to queue
[2025-02-20T04:54:58.833+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:54:58.832+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/sync_postgres_dag.py
[2025-02-20T04:54:58.839+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:54:58.837+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/sync_postgres_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sync_postgres_dag.py", line 4, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2025-02-20T04:54:58.840+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sync_postgres_dag.py
[2025-02-20T04:54:58.873+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sync_postgres_dag.py took 0.051 seconds
[2025-02-20T04:55:29.095+0000] {processor.py:157} INFO - Started process (PID=3670) to work on /opt/airflow/dags/sync_postgres_dag.py
[2025-02-20T04:55:29.096+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sync_postgres_dag.py for tasks to queue
[2025-02-20T04:55:29.098+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:55:29.098+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/sync_postgres_dag.py
[2025-02-20T04:55:29.105+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:55:29.103+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/sync_postgres_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sync_postgres_dag.py", line 4, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2025-02-20T04:55:29.107+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sync_postgres_dag.py
[2025-02-20T04:55:29.142+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sync_postgres_dag.py took 0.052 seconds
[2025-02-20T04:55:59.355+0000] {processor.py:157} INFO - Started process (PID=3679) to work on /opt/airflow/dags/sync_postgres_dag.py
[2025-02-20T04:55:59.357+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sync_postgres_dag.py for tasks to queue
[2025-02-20T04:55:59.361+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:55:59.360+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/sync_postgres_dag.py
[2025-02-20T04:55:59.368+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:55:59.366+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/sync_postgres_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sync_postgres_dag.py", line 4, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2025-02-20T04:55:59.369+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sync_postgres_dag.py
[2025-02-20T04:55:59.400+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sync_postgres_dag.py took 0.049 seconds
[2025-02-20T04:56:29.613+0000] {processor.py:157} INFO - Started process (PID=3688) to work on /opt/airflow/dags/sync_postgres_dag.py
[2025-02-20T04:56:29.614+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sync_postgres_dag.py for tasks to queue
[2025-02-20T04:56:29.617+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:56:29.616+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/sync_postgres_dag.py
[2025-02-20T04:56:29.621+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:56:29.620+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/sync_postgres_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sync_postgres_dag.py", line 4, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2025-02-20T04:56:29.622+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sync_postgres_dag.py
[2025-02-20T04:56:29.650+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sync_postgres_dag.py took 0.041 seconds
[2025-02-20T04:56:59.865+0000] {processor.py:157} INFO - Started process (PID=3697) to work on /opt/airflow/dags/sync_postgres_dag.py
[2025-02-20T04:56:59.867+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sync_postgres_dag.py for tasks to queue
[2025-02-20T04:56:59.869+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:56:59.869+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/sync_postgres_dag.py
[2025-02-20T04:56:59.874+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:56:59.872+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/sync_postgres_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sync_postgres_dag.py", line 4, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2025-02-20T04:56:59.875+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sync_postgres_dag.py
[2025-02-20T04:56:59.911+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sync_postgres_dag.py took 0.051 seconds
