[2025-02-20T04:14:04.718+0000] {processor.py:157} INFO - Started process (PID=2982) to work on /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:14:04.719+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sync_mysql_dag.py for tasks to queue
[2025-02-20T04:14:04.724+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:14:04.724+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:14:04.736+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:14:04.733+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/sync_mysql_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sync_mysql_dag.py", line 4, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2025-02-20T04:14:04.737+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:14:04.766+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sync_mysql_dag.py took 0.058 seconds
[2025-02-20T04:14:14.842+0000] {processor.py:157} INFO - Started process (PID=2983) to work on /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:14:14.878+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sync_mysql_dag.py for tasks to queue
[2025-02-20T04:14:14.882+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:14:14.881+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:14:14.891+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:14:14.889+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/sync_mysql_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sync_mysql_dag.py", line 4, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2025-02-20T04:14:14.892+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:14:14.930+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sync_mysql_dag.py took 0.092 seconds
[2025-02-20T04:14:26.933+0000] {processor.py:157} INFO - Started process (PID=2984) to work on /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:14:26.940+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sync_mysql_dag.py for tasks to queue
[2025-02-20T04:14:26.944+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:14:26.943+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:14:26.954+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:14:26.952+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/sync_mysql_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sync_mysql_dag.py", line 4, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2025-02-20T04:14:26.955+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:14:26.987+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sync_mysql_dag.py took 0.059 seconds
[2025-02-20T04:14:37.012+0000] {processor.py:157} INFO - Started process (PID=2992) to work on /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:14:37.018+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sync_mysql_dag.py for tasks to queue
[2025-02-20T04:14:37.021+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:14:37.020+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:14:37.029+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:14:37.028+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/sync_mysql_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sync_mysql_dag.py", line 4, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2025-02-20T04:14:37.029+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:14:37.068+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sync_mysql_dag.py took 0.060 seconds
[2025-02-20T04:14:51.180+0000] {processor.py:157} INFO - Started process (PID=2993) to work on /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:14:51.185+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sync_mysql_dag.py for tasks to queue
[2025-02-20T04:14:51.188+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:14:51.187+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:14:51.195+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:14:51.193+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/sync_mysql_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sync_mysql_dag.py", line 4, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2025-02-20T04:14:51.195+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:14:51.225+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sync_mysql_dag.py took 0.049 seconds
[2025-02-20T04:15:21.389+0000] {processor.py:157} INFO - Started process (PID=3001) to work on /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:15:21.392+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sync_mysql_dag.py for tasks to queue
[2025-02-20T04:15:21.395+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:15:21.394+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:15:21.399+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:15:21.398+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/sync_mysql_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sync_mysql_dag.py", line 4, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2025-02-20T04:15:21.400+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:15:21.430+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sync_mysql_dag.py took 0.046 seconds
[2025-02-20T04:15:51.617+0000] {processor.py:157} INFO - Started process (PID=3009) to work on /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:15:51.619+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sync_mysql_dag.py for tasks to queue
[2025-02-20T04:15:51.622+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:15:51.621+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:15:51.626+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:15:51.625+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/sync_mysql_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sync_mysql_dag.py", line 4, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2025-02-20T04:15:51.627+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:15:51.658+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sync_mysql_dag.py took 0.044 seconds
[2025-02-20T04:16:21.815+0000] {processor.py:157} INFO - Started process (PID=3017) to work on /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:16:21.830+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sync_mysql_dag.py for tasks to queue
[2025-02-20T04:16:21.834+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:16:21.833+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:16:21.838+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:16:21.837+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/sync_mysql_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sync_mysql_dag.py", line 4, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2025-02-20T04:16:21.839+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:16:21.877+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sync_mysql_dag.py took 0.067 seconds
[2025-02-20T04:16:52.023+0000] {processor.py:157} INFO - Started process (PID=3025) to work on /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:16:52.026+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sync_mysql_dag.py for tasks to queue
[2025-02-20T04:16:52.029+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:16:52.028+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:16:52.034+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:16:52.033+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/sync_mysql_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sync_mysql_dag.py", line 4, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2025-02-20T04:16:52.035+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:16:52.068+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sync_mysql_dag.py took 0.048 seconds
[2025-02-20T04:17:22.261+0000] {processor.py:157} INFO - Started process (PID=3033) to work on /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:17:22.263+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sync_mysql_dag.py for tasks to queue
[2025-02-20T04:17:22.266+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:17:22.265+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:17:22.272+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:17:22.270+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/sync_mysql_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sync_mysql_dag.py", line 4, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2025-02-20T04:17:22.272+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:17:22.304+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sync_mysql_dag.py took 0.047 seconds
[2025-02-20T04:17:52.475+0000] {processor.py:157} INFO - Started process (PID=3041) to work on /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:17:52.477+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sync_mysql_dag.py for tasks to queue
[2025-02-20T04:17:52.480+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:17:52.480+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:17:52.491+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:17:52.485+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/sync_mysql_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sync_mysql_dag.py", line 4, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2025-02-20T04:17:52.492+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:17:52.520+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sync_mysql_dag.py took 0.050 seconds
[2025-02-20T04:18:22.679+0000] {processor.py:157} INFO - Started process (PID=3049) to work on /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:18:22.682+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sync_mysql_dag.py for tasks to queue
[2025-02-20T04:18:22.687+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:18:22.687+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:18:22.694+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:18:22.693+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/sync_mysql_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sync_mysql_dag.py", line 4, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2025-02-20T04:18:22.695+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:18:22.725+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sync_mysql_dag.py took 0.050 seconds
[2025-02-20T04:18:52.910+0000] {processor.py:157} INFO - Started process (PID=3057) to work on /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:18:52.912+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sync_mysql_dag.py for tasks to queue
[2025-02-20T04:18:52.915+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:18:52.914+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:18:52.920+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:18:52.918+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/sync_mysql_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sync_mysql_dag.py", line 4, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2025-02-20T04:18:52.920+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:18:52.959+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sync_mysql_dag.py took 0.056 seconds
[2025-02-20T04:19:23.145+0000] {processor.py:157} INFO - Started process (PID=3065) to work on /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:19:23.149+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sync_mysql_dag.py for tasks to queue
[2025-02-20T04:19:23.152+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:19:23.152+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:19:23.157+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:19:23.156+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/sync_mysql_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sync_mysql_dag.py", line 4, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2025-02-20T04:19:23.158+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:19:23.191+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sync_mysql_dag.py took 0.051 seconds
[2025-02-20T04:19:53.366+0000] {processor.py:157} INFO - Started process (PID=3073) to work on /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:19:53.369+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sync_mysql_dag.py for tasks to queue
[2025-02-20T04:19:53.372+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:19:53.371+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:19:53.376+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:19:53.375+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/sync_mysql_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sync_mysql_dag.py", line 4, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2025-02-20T04:19:53.377+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:19:53.408+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sync_mysql_dag.py took 0.047 seconds
[2025-02-20T04:20:23.587+0000] {processor.py:157} INFO - Started process (PID=3081) to work on /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:20:23.590+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sync_mysql_dag.py for tasks to queue
[2025-02-20T04:20:23.593+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:20:23.593+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:20:23.598+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:20:23.597+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/sync_mysql_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sync_mysql_dag.py", line 4, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2025-02-20T04:20:23.599+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:20:23.632+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sync_mysql_dag.py took 0.048 seconds
[2025-02-20T04:20:53.819+0000] {processor.py:157} INFO - Started process (PID=3089) to work on /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:20:53.821+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sync_mysql_dag.py for tasks to queue
[2025-02-20T04:20:53.823+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:20:53.823+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:20:53.828+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:20:53.827+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/sync_mysql_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sync_mysql_dag.py", line 4, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2025-02-20T04:20:53.829+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:20:53.860+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sync_mysql_dag.py took 0.046 seconds
[2025-02-20T04:21:24.031+0000] {processor.py:157} INFO - Started process (PID=3097) to work on /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:21:24.033+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sync_mysql_dag.py for tasks to queue
[2025-02-20T04:21:24.036+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:21:24.036+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:21:24.041+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:21:24.040+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/sync_mysql_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sync_mysql_dag.py", line 4, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2025-02-20T04:21:24.042+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:21:24.081+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sync_mysql_dag.py took 0.054 seconds
[2025-02-20T04:21:54.241+0000] {processor.py:157} INFO - Started process (PID=3105) to work on /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:21:54.243+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sync_mysql_dag.py for tasks to queue
[2025-02-20T04:21:54.247+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:21:54.246+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:21:54.252+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:21:54.251+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/sync_mysql_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sync_mysql_dag.py", line 4, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2025-02-20T04:21:54.252+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:21:54.284+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sync_mysql_dag.py took 0.047 seconds
[2025-02-20T04:22:24.464+0000] {processor.py:157} INFO - Started process (PID=3112) to work on /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:22:24.467+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sync_mysql_dag.py for tasks to queue
[2025-02-20T04:22:24.470+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:22:24.469+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:22:24.475+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:22:24.474+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/sync_mysql_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sync_mysql_dag.py", line 4, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2025-02-20T04:22:24.476+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:22:24.512+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sync_mysql_dag.py took 0.052 seconds
[2025-02-20T04:22:54.701+0000] {processor.py:157} INFO - Started process (PID=3120) to work on /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:22:54.705+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sync_mysql_dag.py for tasks to queue
[2025-02-20T04:22:54.708+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:22:54.707+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:22:54.716+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:22:54.714+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/sync_mysql_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sync_mysql_dag.py", line 4, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2025-02-20T04:22:54.716+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:22:54.758+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sync_mysql_dag.py took 0.060 seconds
[2025-02-20T04:23:24.913+0000] {processor.py:157} INFO - Started process (PID=3128) to work on /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:23:24.916+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sync_mysql_dag.py for tasks to queue
[2025-02-20T04:23:24.918+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:23:24.918+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:23:24.923+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:23:24.922+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/sync_mysql_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sync_mysql_dag.py", line 4, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2025-02-20T04:23:24.923+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:23:24.955+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sync_mysql_dag.py took 0.046 seconds
[2025-02-20T04:23:55.157+0000] {processor.py:157} INFO - Started process (PID=3136) to work on /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:23:55.160+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sync_mysql_dag.py for tasks to queue
[2025-02-20T04:23:55.163+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:23:55.162+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:23:55.168+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:23:55.166+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/sync_mysql_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sync_mysql_dag.py", line 4, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2025-02-20T04:23:55.169+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:23:55.200+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sync_mysql_dag.py took 0.047 seconds
[2025-02-20T04:24:25.379+0000] {processor.py:157} INFO - Started process (PID=3144) to work on /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:24:25.380+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sync_mysql_dag.py for tasks to queue
[2025-02-20T04:24:25.383+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:24:25.382+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:24:25.389+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:24:25.387+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/sync_mysql_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sync_mysql_dag.py", line 4, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2025-02-20T04:24:25.389+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:24:25.420+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sync_mysql_dag.py took 0.044 seconds
[2025-02-20T04:24:55.575+0000] {processor.py:157} INFO - Started process (PID=3152) to work on /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:24:55.577+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sync_mysql_dag.py for tasks to queue
[2025-02-20T04:24:55.580+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:24:55.580+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:24:55.588+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:24:55.584+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/sync_mysql_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sync_mysql_dag.py", line 4, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2025-02-20T04:24:55.589+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:24:55.623+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sync_mysql_dag.py took 0.052 seconds
[2025-02-20T04:25:25.792+0000] {processor.py:157} INFO - Started process (PID=3160) to work on /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:25:25.793+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sync_mysql_dag.py for tasks to queue
[2025-02-20T04:25:25.796+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:25:25.796+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:25:25.800+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:25:25.799+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/sync_mysql_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sync_mysql_dag.py", line 4, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2025-02-20T04:25:25.801+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:25:25.832+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sync_mysql_dag.py took 0.045 seconds
[2025-02-20T04:25:56.008+0000] {processor.py:157} INFO - Started process (PID=3168) to work on /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:25:56.012+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sync_mysql_dag.py for tasks to queue
[2025-02-20T04:25:56.015+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:25:56.014+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:25:56.020+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:25:56.018+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/sync_mysql_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sync_mysql_dag.py", line 4, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2025-02-20T04:25:56.020+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:25:56.044+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sync_mysql_dag.py took 0.043 seconds
[2025-02-20T04:26:26.215+0000] {processor.py:157} INFO - Started process (PID=3176) to work on /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:26:26.216+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sync_mysql_dag.py for tasks to queue
[2025-02-20T04:26:26.218+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:26:26.218+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:26:26.223+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:26:26.221+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/sync_mysql_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sync_mysql_dag.py", line 4, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2025-02-20T04:26:26.223+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:26:26.257+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sync_mysql_dag.py took 0.045 seconds
[2025-02-20T04:26:56.429+0000] {processor.py:157} INFO - Started process (PID=3183) to work on /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:26:56.431+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sync_mysql_dag.py for tasks to queue
[2025-02-20T04:26:56.434+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:26:56.433+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:26:56.438+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:26:56.437+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/sync_mysql_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sync_mysql_dag.py", line 4, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2025-02-20T04:26:56.439+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:26:56.470+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sync_mysql_dag.py took 0.045 seconds
[2025-02-20T04:27:26.630+0000] {processor.py:157} INFO - Started process (PID=3191) to work on /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:27:26.631+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sync_mysql_dag.py for tasks to queue
[2025-02-20T04:27:26.633+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:27:26.633+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:27:26.638+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:27:26.636+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/sync_mysql_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sync_mysql_dag.py", line 4, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2025-02-20T04:27:26.638+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:27:26.670+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sync_mysql_dag.py took 0.044 seconds
[2025-02-20T04:27:56.852+0000] {processor.py:157} INFO - Started process (PID=3199) to work on /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:27:56.856+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sync_mysql_dag.py for tasks to queue
[2025-02-20T04:27:56.859+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:27:56.859+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:27:56.864+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:27:56.863+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/sync_mysql_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sync_mysql_dag.py", line 4, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2025-02-20T04:27:56.865+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:27:56.897+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sync_mysql_dag.py took 0.050 seconds
[2025-02-20T04:28:27.069+0000] {processor.py:157} INFO - Started process (PID=3207) to work on /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:28:27.070+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sync_mysql_dag.py for tasks to queue
[2025-02-20T04:28:27.073+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:28:27.072+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:28:27.078+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:28:27.076+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/sync_mysql_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sync_mysql_dag.py", line 4, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2025-02-20T04:28:27.078+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:28:27.114+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sync_mysql_dag.py took 0.049 seconds
[2025-02-20T04:28:57.294+0000] {processor.py:157} INFO - Started process (PID=3215) to work on /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:28:57.296+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sync_mysql_dag.py for tasks to queue
[2025-02-20T04:28:57.299+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:28:57.298+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:28:57.303+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:28:57.302+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/sync_mysql_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sync_mysql_dag.py", line 4, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2025-02-20T04:28:57.304+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:28:57.334+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sync_mysql_dag.py took 0.045 seconds
[2025-02-20T04:29:27.507+0000] {processor.py:157} INFO - Started process (PID=3223) to work on /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:29:27.508+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sync_mysql_dag.py for tasks to queue
[2025-02-20T04:29:27.511+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:29:27.510+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:29:27.516+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:29:27.515+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/sync_mysql_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sync_mysql_dag.py", line 4, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2025-02-20T04:29:27.517+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:29:27.557+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sync_mysql_dag.py took 0.056 seconds
[2025-02-20T04:29:57.699+0000] {processor.py:157} INFO - Started process (PID=3230) to work on /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:29:57.701+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sync_mysql_dag.py for tasks to queue
[2025-02-20T04:29:57.705+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:29:57.705+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:29:57.711+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:29:57.709+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/sync_mysql_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sync_mysql_dag.py", line 4, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2025-02-20T04:29:57.711+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:29:57.744+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sync_mysql_dag.py took 0.049 seconds
[2025-02-20T04:30:27.908+0000] {processor.py:157} INFO - Started process (PID=3238) to work on /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:30:27.909+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sync_mysql_dag.py for tasks to queue
[2025-02-20T04:30:27.912+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:30:27.911+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:30:27.917+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:30:27.916+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/sync_mysql_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sync_mysql_dag.py", line 4, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2025-02-20T04:30:27.917+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:30:27.957+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sync_mysql_dag.py took 0.053 seconds
[2025-02-20T04:30:58.110+0000] {processor.py:157} INFO - Started process (PID=3246) to work on /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:30:58.112+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sync_mysql_dag.py for tasks to queue
[2025-02-20T04:30:58.115+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:30:58.115+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:30:58.121+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:30:58.119+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/sync_mysql_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sync_mysql_dag.py", line 4, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2025-02-20T04:30:58.122+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:30:58.158+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sync_mysql_dag.py took 0.053 seconds
[2025-02-20T04:31:28.332+0000] {processor.py:157} INFO - Started process (PID=3254) to work on /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:31:28.333+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sync_mysql_dag.py for tasks to queue
[2025-02-20T04:31:28.335+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:31:28.335+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:31:28.340+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:31:28.339+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/sync_mysql_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sync_mysql_dag.py", line 4, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2025-02-20T04:31:28.340+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:31:28.367+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sync_mysql_dag.py took 0.038 seconds
[2025-02-20T04:31:58.555+0000] {processor.py:157} INFO - Started process (PID=3262) to work on /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:31:58.557+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sync_mysql_dag.py for tasks to queue
[2025-02-20T04:31:58.560+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:31:58.559+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:31:58.566+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:31:58.564+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/sync_mysql_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sync_mysql_dag.py", line 4, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2025-02-20T04:31:58.567+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:31:58.599+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sync_mysql_dag.py took 0.048 seconds
[2025-02-20T04:32:28.753+0000] {processor.py:157} INFO - Started process (PID=3270) to work on /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:32:28.754+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sync_mysql_dag.py for tasks to queue
[2025-02-20T04:32:28.757+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:32:28.756+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:32:28.762+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:32:28.761+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/sync_mysql_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sync_mysql_dag.py", line 4, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2025-02-20T04:32:28.763+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:32:28.793+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sync_mysql_dag.py took 0.043 seconds
[2025-02-20T04:32:58.974+0000] {processor.py:157} INFO - Started process (PID=3278) to work on /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:32:58.976+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sync_mysql_dag.py for tasks to queue
[2025-02-20T04:32:58.979+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:32:58.979+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:32:58.983+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:32:58.982+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/sync_mysql_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sync_mysql_dag.py", line 4, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2025-02-20T04:32:58.984+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:32:59.013+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sync_mysql_dag.py took 0.043 seconds
[2025-02-20T04:33:29.164+0000] {processor.py:157} INFO - Started process (PID=3286) to work on /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:33:29.165+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sync_mysql_dag.py for tasks to queue
[2025-02-20T04:33:29.167+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:33:29.167+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:33:29.173+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:33:29.172+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/sync_mysql_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sync_mysql_dag.py", line 4, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2025-02-20T04:33:29.174+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:33:29.206+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sync_mysql_dag.py took 0.046 seconds
[2025-02-20T04:33:59.370+0000] {processor.py:157} INFO - Started process (PID=3294) to work on /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:33:59.372+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sync_mysql_dag.py for tasks to queue
[2025-02-20T04:33:59.375+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:33:59.375+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:33:59.380+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:33:59.378+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/sync_mysql_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sync_mysql_dag.py", line 4, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2025-02-20T04:33:59.380+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:33:59.422+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sync_mysql_dag.py took 0.055 seconds
[2025-02-20T04:34:29.599+0000] {processor.py:157} INFO - Started process (PID=3302) to work on /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:34:29.600+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sync_mysql_dag.py for tasks to queue
[2025-02-20T04:34:29.605+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:34:29.605+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:34:29.612+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:34:29.611+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/sync_mysql_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sync_mysql_dag.py", line 4, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2025-02-20T04:34:29.612+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:34:29.644+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sync_mysql_dag.py took 0.048 seconds
[2025-02-20T04:34:59.821+0000] {processor.py:157} INFO - Started process (PID=3310) to work on /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:34:59.823+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sync_mysql_dag.py for tasks to queue
[2025-02-20T04:34:59.828+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:34:59.828+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:34:59.834+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:34:59.832+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/sync_mysql_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sync_mysql_dag.py", line 4, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2025-02-20T04:34:59.834+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:34:59.865+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sync_mysql_dag.py took 0.049 seconds
[2025-02-20T04:35:30.054+0000] {processor.py:157} INFO - Started process (PID=3318) to work on /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:35:30.055+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sync_mysql_dag.py for tasks to queue
[2025-02-20T04:35:30.057+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:35:30.057+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:35:30.062+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:35:30.061+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/sync_mysql_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sync_mysql_dag.py", line 4, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2025-02-20T04:35:30.062+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:35:30.118+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sync_mysql_dag.py took 0.068 seconds
[2025-02-20T04:36:00.274+0000] {processor.py:157} INFO - Started process (PID=3326) to work on /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:36:00.277+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sync_mysql_dag.py for tasks to queue
[2025-02-20T04:36:00.280+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:36:00.279+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:36:00.284+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:36:00.283+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/sync_mysql_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sync_mysql_dag.py", line 4, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2025-02-20T04:36:00.285+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:36:00.317+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sync_mysql_dag.py took 0.046 seconds
[2025-02-20T04:36:30.512+0000] {processor.py:157} INFO - Started process (PID=3334) to work on /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:36:30.513+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sync_mysql_dag.py for tasks to queue
[2025-02-20T04:36:30.516+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:36:30.515+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:36:30.520+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:36:30.519+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/sync_mysql_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sync_mysql_dag.py", line 4, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2025-02-20T04:36:30.521+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:36:30.555+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sync_mysql_dag.py took 0.047 seconds
[2025-02-20T04:37:00.713+0000] {processor.py:157} INFO - Started process (PID=3342) to work on /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:37:00.716+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sync_mysql_dag.py for tasks to queue
[2025-02-20T04:37:00.718+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:37:00.718+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:37:00.723+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:37:00.722+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/sync_mysql_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sync_mysql_dag.py", line 4, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2025-02-20T04:37:00.724+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:37:00.757+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sync_mysql_dag.py took 0.048 seconds
[2025-02-20T04:37:30.914+0000] {processor.py:157} INFO - Started process (PID=3350) to work on /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:37:30.915+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sync_mysql_dag.py for tasks to queue
[2025-02-20T04:37:30.917+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:37:30.917+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:37:30.922+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:37:30.921+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/sync_mysql_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sync_mysql_dag.py", line 4, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2025-02-20T04:37:30.923+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:37:30.957+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sync_mysql_dag.py took 0.047 seconds
[2025-02-20T04:38:01.141+0000] {processor.py:157} INFO - Started process (PID=3358) to work on /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:38:01.143+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sync_mysql_dag.py for tasks to queue
[2025-02-20T04:38:01.146+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:38:01.145+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:38:01.151+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:38:01.149+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/sync_mysql_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sync_mysql_dag.py", line 4, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2025-02-20T04:38:01.151+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:38:01.181+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sync_mysql_dag.py took 0.043 seconds
[2025-02-20T04:38:31.340+0000] {processor.py:157} INFO - Started process (PID=3366) to work on /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:38:31.341+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sync_mysql_dag.py for tasks to queue
[2025-02-20T04:38:31.344+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:38:31.343+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:38:31.349+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:38:31.348+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/sync_mysql_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sync_mysql_dag.py", line 4, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2025-02-20T04:38:31.349+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:38:31.379+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sync_mysql_dag.py took 0.043 seconds
[2025-02-20T04:39:01.568+0000] {processor.py:157} INFO - Started process (PID=3374) to work on /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:39:01.571+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sync_mysql_dag.py for tasks to queue
[2025-02-20T04:39:01.574+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:39:01.573+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:39:01.578+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:39:01.577+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/sync_mysql_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sync_mysql_dag.py", line 4, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2025-02-20T04:39:01.579+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:39:01.611+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sync_mysql_dag.py took 0.047 seconds
[2025-02-20T04:39:31.792+0000] {processor.py:157} INFO - Started process (PID=3382) to work on /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:39:31.793+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sync_mysql_dag.py for tasks to queue
[2025-02-20T04:39:31.795+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:39:31.795+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:39:31.800+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:39:31.798+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/sync_mysql_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sync_mysql_dag.py", line 4, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2025-02-20T04:39:31.800+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:39:31.831+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sync_mysql_dag.py took 0.043 seconds
[2025-02-20T04:40:01.989+0000] {processor.py:157} INFO - Started process (PID=3390) to work on /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:40:01.991+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sync_mysql_dag.py for tasks to queue
[2025-02-20T04:40:01.994+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:40:01.993+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:40:01.998+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:40:01.997+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/sync_mysql_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sync_mysql_dag.py", line 4, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2025-02-20T04:40:01.999+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:40:02.038+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sync_mysql_dag.py took 0.052 seconds
[2025-02-20T04:40:32.232+0000] {processor.py:157} INFO - Started process (PID=3398) to work on /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:40:32.233+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sync_mysql_dag.py for tasks to queue
[2025-02-20T04:40:32.236+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:40:32.235+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:40:32.240+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:40:32.239+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/sync_mysql_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sync_mysql_dag.py", line 4, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2025-02-20T04:40:32.241+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:40:32.277+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sync_mysql_dag.py took 0.049 seconds
[2025-02-20T04:41:02.441+0000] {processor.py:157} INFO - Started process (PID=3406) to work on /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:41:02.444+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sync_mysql_dag.py for tasks to queue
[2025-02-20T04:41:02.446+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:41:02.446+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:41:02.451+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:41:02.450+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/sync_mysql_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sync_mysql_dag.py", line 4, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2025-02-20T04:41:02.452+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:41:02.483+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sync_mysql_dag.py took 0.045 seconds
[2025-02-20T04:41:32.663+0000] {processor.py:157} INFO - Started process (PID=3414) to work on /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:41:32.664+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sync_mysql_dag.py for tasks to queue
[2025-02-20T04:41:32.666+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:41:32.666+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:41:32.671+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:41:32.670+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/sync_mysql_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sync_mysql_dag.py", line 4, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2025-02-20T04:41:32.672+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:41:32.705+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sync_mysql_dag.py took 0.045 seconds
[2025-02-20T04:42:02.859+0000] {processor.py:157} INFO - Started process (PID=3422) to work on /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:42:02.861+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sync_mysql_dag.py for tasks to queue
[2025-02-20T04:42:02.864+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:42:02.863+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:42:02.868+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:42:02.867+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/sync_mysql_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sync_mysql_dag.py", line 4, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2025-02-20T04:42:02.869+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:42:02.895+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sync_mysql_dag.py took 0.040 seconds
[2025-02-20T04:42:33.084+0000] {processor.py:157} INFO - Started process (PID=3430) to work on /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:42:33.086+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sync_mysql_dag.py for tasks to queue
[2025-02-20T04:42:33.089+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:42:33.088+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:42:33.093+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:42:33.092+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/sync_mysql_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sync_mysql_dag.py", line 4, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2025-02-20T04:42:33.093+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:42:33.128+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sync_mysql_dag.py took 0.048 seconds
[2025-02-20T04:43:03.298+0000] {processor.py:157} INFO - Started process (PID=3438) to work on /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:43:03.300+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sync_mysql_dag.py for tasks to queue
[2025-02-20T04:43:03.303+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:43:03.303+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:43:03.307+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:43:03.306+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/sync_mysql_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sync_mysql_dag.py", line 4, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2025-02-20T04:43:03.308+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:43:03.336+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sync_mysql_dag.py took 0.042 seconds
[2025-02-20T04:43:33.501+0000] {processor.py:157} INFO - Started process (PID=3446) to work on /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:43:33.502+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sync_mysql_dag.py for tasks to queue
[2025-02-20T04:43:33.505+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:43:33.504+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:43:33.509+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:43:33.508+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/sync_mysql_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sync_mysql_dag.py", line 4, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2025-02-20T04:43:33.510+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:43:33.541+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sync_mysql_dag.py took 0.044 seconds
[2025-02-20T04:44:03.720+0000] {processor.py:157} INFO - Started process (PID=3454) to work on /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:44:03.722+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sync_mysql_dag.py for tasks to queue
[2025-02-20T04:44:03.725+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:44:03.725+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:44:03.729+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:44:03.728+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/sync_mysql_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sync_mysql_dag.py", line 4, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2025-02-20T04:44:03.730+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:44:03.762+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sync_mysql_dag.py took 0.045 seconds
[2025-02-20T04:44:33.993+0000] {processor.py:157} INFO - Started process (PID=3462) to work on /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:44:33.994+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sync_mysql_dag.py for tasks to queue
[2025-02-20T04:44:33.997+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:44:33.997+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:44:34.008+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:44:34.004+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/sync_mysql_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sync_mysql_dag.py", line 4, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2025-02-20T04:44:34.010+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:44:34.053+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sync_mysql_dag.py took 0.063 seconds
[2025-02-20T04:45:04.274+0000] {processor.py:157} INFO - Started process (PID=3471) to work on /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:45:04.277+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sync_mysql_dag.py for tasks to queue
[2025-02-20T04:45:04.279+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:45:04.279+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:45:04.284+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:45:04.283+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/sync_mysql_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sync_mysql_dag.py", line 4, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2025-02-20T04:45:04.285+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:45:04.316+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sync_mysql_dag.py took 0.045 seconds
[2025-02-20T04:45:34.536+0000] {processor.py:157} INFO - Started process (PID=3480) to work on /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:45:34.537+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sync_mysql_dag.py for tasks to queue
[2025-02-20T04:45:34.539+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:45:34.539+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:45:34.545+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:45:34.543+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/sync_mysql_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sync_mysql_dag.py", line 4, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2025-02-20T04:45:34.546+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:45:34.580+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sync_mysql_dag.py took 0.048 seconds
[2025-02-20T04:46:04.802+0000] {processor.py:157} INFO - Started process (PID=3489) to work on /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:46:04.805+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sync_mysql_dag.py for tasks to queue
[2025-02-20T04:46:04.808+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:46:04.807+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:46:04.813+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:46:04.812+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/sync_mysql_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sync_mysql_dag.py", line 4, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2025-02-20T04:46:04.814+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:46:04.852+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sync_mysql_dag.py took 0.054 seconds
[2025-02-20T04:46:35.068+0000] {processor.py:157} INFO - Started process (PID=3498) to work on /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:46:35.070+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sync_mysql_dag.py for tasks to queue
[2025-02-20T04:46:35.072+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:46:35.072+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:46:35.076+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:46:35.075+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/sync_mysql_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sync_mysql_dag.py", line 4, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2025-02-20T04:46:35.077+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:46:35.114+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sync_mysql_dag.py took 0.051 seconds
[2025-02-20T04:47:05.353+0000] {processor.py:157} INFO - Started process (PID=3508) to work on /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:47:05.355+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sync_mysql_dag.py for tasks to queue
[2025-02-20T04:47:05.363+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:47:05.363+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:47:05.376+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:47:05.373+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/sync_mysql_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sync_mysql_dag.py", line 4, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2025-02-20T04:47:05.376+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:47:05.419+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sync_mysql_dag.py took 0.070 seconds
[2025-02-20T04:47:35.656+0000] {processor.py:157} INFO - Started process (PID=3517) to work on /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:47:35.657+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sync_mysql_dag.py for tasks to queue
[2025-02-20T04:47:35.659+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:47:35.659+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:47:35.664+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:47:35.662+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/sync_mysql_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sync_mysql_dag.py", line 4, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2025-02-20T04:47:35.665+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:47:35.699+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sync_mysql_dag.py took 0.047 seconds
[2025-02-20T04:48:06.091+0000] {processor.py:157} INFO - Started process (PID=3532) to work on /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:48:06.142+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sync_mysql_dag.py for tasks to queue
[2025-02-20T04:48:06.144+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:48:06.144+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:48:06.150+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:48:06.148+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/sync_mysql_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sync_mysql_dag.py", line 4, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2025-02-20T04:48:06.150+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:48:06.178+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sync_mysql_dag.py took 0.095 seconds
[2025-02-20T04:48:27.345+0000] {processor.py:157} INFO - Started process (PID=3542) to work on /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:48:27.346+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sync_mysql_dag.py for tasks to queue
[2025-02-20T04:48:27.348+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:48:27.348+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:48:27.354+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:48:27.353+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/sync_mysql_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sync_mysql_dag.py", line 4, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2025-02-20T04:48:27.355+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:48:27.385+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sync_mysql_dag.py took 0.044 seconds
[2025-02-20T04:48:31.418+0000] {processor.py:157} INFO - Started process (PID=3543) to work on /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:48:31.419+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sync_mysql_dag.py for tasks to queue
[2025-02-20T04:48:31.423+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:48:31.422+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:48:31.430+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:48:31.429+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/sync_mysql_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sync_mysql_dag.py", line 4, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2025-02-20T04:48:31.431+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:48:31.464+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sync_mysql_dag.py took 0.049 seconds
[2025-02-20T04:48:35.467+0000] {processor.py:157} INFO - Started process (PID=3544) to work on /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:48:35.468+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sync_mysql_dag.py for tasks to queue
[2025-02-20T04:48:35.470+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:48:35.470+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:48:35.477+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:48:35.475+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/sync_mysql_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sync_mysql_dag.py", line 4, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2025-02-20T04:48:35.477+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:48:35.509+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sync_mysql_dag.py took 0.047 seconds
[2025-02-20T04:48:43.591+0000] {processor.py:157} INFO - Started process (PID=3551) to work on /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:48:43.593+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sync_mysql_dag.py for tasks to queue
[2025-02-20T04:48:43.596+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:48:43.595+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:48:43.604+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:48:43.602+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/sync_mysql_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sync_mysql_dag.py", line 4, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2025-02-20T04:48:43.605+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:48:43.638+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sync_mysql_dag.py took 0.052 seconds
[2025-02-20T04:49:13.882+0000] {processor.py:157} INFO - Started process (PID=3561) to work on /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:49:13.883+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sync_mysql_dag.py for tasks to queue
[2025-02-20T04:49:13.886+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:49:13.885+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:49:13.892+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:49:13.890+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/sync_mysql_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sync_mysql_dag.py", line 4, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2025-02-20T04:49:13.892+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:49:13.926+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sync_mysql_dag.py took 0.047 seconds
[2025-02-20T04:49:44.145+0000] {processor.py:157} INFO - Started process (PID=3570) to work on /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:49:44.149+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sync_mysql_dag.py for tasks to queue
[2025-02-20T04:49:44.151+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:49:44.151+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:49:44.156+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:49:44.154+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/sync_mysql_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sync_mysql_dag.py", line 4, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2025-02-20T04:49:44.156+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:49:44.188+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sync_mysql_dag.py took 0.047 seconds
[2025-02-20T04:50:14.394+0000] {processor.py:157} INFO - Started process (PID=3579) to work on /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:50:14.395+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sync_mysql_dag.py for tasks to queue
[2025-02-20T04:50:14.397+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:50:14.397+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:50:14.403+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:50:14.400+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/sync_mysql_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sync_mysql_dag.py", line 4, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2025-02-20T04:50:14.404+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:50:14.440+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sync_mysql_dag.py took 0.050 seconds
[2025-02-20T04:50:44.658+0000] {processor.py:157} INFO - Started process (PID=3588) to work on /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:50:44.661+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sync_mysql_dag.py for tasks to queue
[2025-02-20T04:50:44.665+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:50:44.664+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:50:44.670+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:50:44.668+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/sync_mysql_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sync_mysql_dag.py", line 4, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2025-02-20T04:50:44.670+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:50:44.702+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sync_mysql_dag.py took 0.048 seconds
[2025-02-20T04:51:14.912+0000] {processor.py:157} INFO - Started process (PID=3597) to work on /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:51:14.912+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sync_mysql_dag.py for tasks to queue
[2025-02-20T04:51:14.915+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:51:14.914+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:51:14.928+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:51:14.926+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/sync_mysql_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sync_mysql_dag.py", line 4, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2025-02-20T04:51:14.928+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:51:14.957+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sync_mysql_dag.py took 0.049 seconds
[2025-02-20T04:51:45.194+0000] {processor.py:157} INFO - Started process (PID=3606) to work on /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:51:45.199+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sync_mysql_dag.py for tasks to queue
[2025-02-20T04:51:45.202+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:51:45.202+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:51:45.207+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:51:45.206+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/sync_mysql_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sync_mysql_dag.py", line 4, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2025-02-20T04:51:45.207+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:51:45.237+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sync_mysql_dag.py took 0.047 seconds
[2025-02-20T04:52:15.436+0000] {processor.py:157} INFO - Started process (PID=3615) to work on /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:52:15.436+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sync_mysql_dag.py for tasks to queue
[2025-02-20T04:52:15.439+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:52:15.438+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:52:15.444+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:52:15.442+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/sync_mysql_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sync_mysql_dag.py", line 4, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2025-02-20T04:52:15.444+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:52:15.476+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sync_mysql_dag.py took 0.044 seconds
[2025-02-20T04:52:45.679+0000] {processor.py:157} INFO - Started process (PID=3624) to work on /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:52:45.681+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sync_mysql_dag.py for tasks to queue
[2025-02-20T04:52:45.684+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:52:45.683+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:52:45.688+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:52:45.687+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/sync_mysql_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sync_mysql_dag.py", line 4, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2025-02-20T04:52:45.688+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:52:45.718+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sync_mysql_dag.py took 0.043 seconds
[2025-02-20T04:53:15.930+0000] {processor.py:157} INFO - Started process (PID=3633) to work on /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:53:15.931+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sync_mysql_dag.py for tasks to queue
[2025-02-20T04:53:15.934+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:53:15.933+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:53:15.938+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:53:15.937+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/sync_mysql_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sync_mysql_dag.py", line 4, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2025-02-20T04:53:15.939+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:53:15.977+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sync_mysql_dag.py took 0.053 seconds
[2025-02-20T04:53:46.190+0000] {processor.py:157} INFO - Started process (PID=3642) to work on /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:53:46.194+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sync_mysql_dag.py for tasks to queue
[2025-02-20T04:53:46.197+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:53:46.196+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:53:46.203+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:53:46.200+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/sync_mysql_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sync_mysql_dag.py", line 4, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2025-02-20T04:53:46.204+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:53:46.239+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sync_mysql_dag.py took 0.053 seconds
[2025-02-20T04:54:16.470+0000] {processor.py:157} INFO - Started process (PID=3651) to work on /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:54:16.471+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sync_mysql_dag.py for tasks to queue
[2025-02-20T04:54:16.474+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:54:16.473+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:54:16.478+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:54:16.477+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/sync_mysql_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sync_mysql_dag.py", line 4, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2025-02-20T04:54:16.479+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:54:16.512+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sync_mysql_dag.py took 0.045 seconds
[2025-02-20T04:54:46.731+0000] {processor.py:157} INFO - Started process (PID=3660) to work on /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:54:46.744+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sync_mysql_dag.py for tasks to queue
[2025-02-20T04:54:46.747+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:54:46.746+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:54:46.751+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:54:46.750+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/sync_mysql_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sync_mysql_dag.py", line 4, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2025-02-20T04:54:46.752+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:54:46.780+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sync_mysql_dag.py took 0.053 seconds
[2025-02-20T04:55:16.995+0000] {processor.py:157} INFO - Started process (PID=3669) to work on /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:55:16.996+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sync_mysql_dag.py for tasks to queue
[2025-02-20T04:55:16.999+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:55:16.998+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:55:17.003+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:55:17.002+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/sync_mysql_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sync_mysql_dag.py", line 4, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2025-02-20T04:55:17.004+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:55:17.043+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sync_mysql_dag.py took 0.052 seconds
[2025-02-20T04:55:47.264+0000] {processor.py:157} INFO - Started process (PID=3678) to work on /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:55:47.267+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sync_mysql_dag.py for tasks to queue
[2025-02-20T04:55:47.269+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:55:47.269+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:55:47.274+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:55:47.273+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/sync_mysql_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sync_mysql_dag.py", line 4, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2025-02-20T04:55:47.275+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:55:47.312+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sync_mysql_dag.py took 0.053 seconds
[2025-02-20T04:56:17.519+0000] {processor.py:157} INFO - Started process (PID=3687) to work on /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:56:17.520+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sync_mysql_dag.py for tasks to queue
[2025-02-20T04:56:17.523+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:56:17.522+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:56:17.527+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:56:17.526+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/sync_mysql_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sync_mysql_dag.py", line 4, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2025-02-20T04:56:17.528+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:56:17.559+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sync_mysql_dag.py took 0.045 seconds
[2025-02-20T04:56:47.768+0000] {processor.py:157} INFO - Started process (PID=3696) to work on /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:56:47.770+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/sync_mysql_dag.py for tasks to queue
[2025-02-20T04:56:47.774+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:56:47.773+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:56:47.781+0000] {logging_mixin.py:154} INFO - [2025-02-20T04:56:47.780+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/sync_mysql_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sync_mysql_dag.py", line 4, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2025-02-20T04:56:47.782+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/sync_mysql_dag.py
[2025-02-20T04:56:47.820+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/sync_mysql_dag.py took 0.057 seconds
